spring :
  profiles :
    active : local
---


spring :
  profiles: local
  session :
    timeout: 600
  jwt:
    secret : jwtsecretkey
  datasource:
    #로그 없이 작동 - 개발 MYSQL
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/stock?serverTimezone=UTC&characterEncoding=UTF-8
    #로그 표시하며 작동 - 개발
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/etc?serverTimezone=UTC&characterEncoding=UTF-8
    username: sungchul
    password: sungchul1234

  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled : true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\IntellijProject\\sungchul_ETC\\file
    encoding :
      encoding :
        charset : UTF-8
        force : true

  jackson:
    default-property-inclusion: NON_NULL
server :
  port : 8080
  session:
    timeout : 600
  error:
    path: /error
    include-message : always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
    whitelabel:
      enabled: true

mybatis:
  #config-location : classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null

swagger :
  enable : true




---
spring:
  profiles: prod
  session:
    timeout: 600
  datasource:
    #로그 없이 작동 - 개발 MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/etc?serverTimezone=UTC&characterEncoding=UTF-8


    username: sungchul
    password: sungchul1234
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\sungchul_ETC\\file
  jackson:
    default-property-inclusion: NON_NULL
server:
  port: 9090
  session:
    timeout: 600
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null
swagger:
  enable: true

